after_script: greenkeeper-lockfile-upload
before_install: npm install npm@latest --global
before_script: greenkeeper-lockfile-update
env:
  global:
  - secure: pN1nzdcGaBJaYetPm/j8xfjSDlFeRhaYBv5AX+N3Zi2xCVg+dJU6eSKx/F7mprwaHMlLx6s7gNs/wN/3UB3FyxJVVq12gBSMtMb0L9CTDICgtifl6epatC/m3O+c/REcYAIC9gXtTFKyCx85eWzNyP9M5MGRZ+EjbIWLTTdL2TXzYzTxj8DIpyLA6/CneQ15Damohf7+xa78/vH8Z6943FRaaCZml+fbG4bXNVdJnyShD5LewJGUnIV4RyArkiAH10fYmXPcVDvrAOrSUO3l5ZZxczd1MX+CeyXbDrlfatkwcFZrhMKoQmfSyfPOMqPyOoEbpXpzK4XKxRefHcKm24GuaWwMKndYE/KOE0+X8Dmy1hoPPHlFIDJstivIJOgji91VlaBeD6V0dSpPuubDX0BtblwgqgFI0l0yzPEw+EzLinTZTQRvLnllM/9jtqkH6YlvryDOB4lGgYmFGHZ/Kq2hnihUU1a++NoRuK7Yn+2Wl6lHAkwaqzPjapb37GtDr3f3Db3oiHetg9MWMq7y1+WsYOp7egQQCvvD9yFhGH02QYnj/OTAlkTsIfIQjFWX9xp3BYpyecdBvEyiOjr08/7ZSF1ybI3/BfyC3B5uPGaDEuDW09cY0TFPnnoJ7GgsDRzwW7VpP4Q7719TZZjT28zyuHTq0YgbaW7/o2br2jA=
language: node_js
node_js: 6
sudo: false
